# Generated by Django 4.2.7 on 2023-11-28 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Chat_Bot', '0001_initial'),
    ]

    operations = [
    ]
