# Generated by Django 4.2.7 on 2023-11-28 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Chat_Bot', '0002_auto_20231128_1129'),
    ]

    operations = [
    ]
