# Generated by Django 4.2.7 on 2023-11-28 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chat_Bot', '0006_delete_customuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='password1',
            field=models.CharField(default='', max_length=255),
        ),
    ]
